services:
  - type: web
    name: fp-rag-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: false

    envVars:
      - key: PINECONE_API_KEY
        sync: false

      - key: INDEX_NAME
        sync: false

      - key: GROQ_API_KEY
        sync: false

      - key: COHERE_API_KEY
        sync: false